version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gerhuhaer
      MYSQL_DATABASE: test_database
      MYSQL_USER: watabou
      MYSQL_PASSWORD: faweufhli

  db_app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: test_database
      MYSQL_PORT: 3306
      MYSQL_USER: watabou
      MYSQL_PASSWORD: faweufhli
    restart: always

volumes:
  mysql_data: